# -*- coding: utf-8 -*-
"""ml prac 4 sanika

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_gOQYuKCrsE0dW9B8fgrQdJp5NTSX4Vy

Sanika Takarkhede(CS3016)

ML LAB-4 AIM: To build and evaluate a Decision Tree model for classification tasks and study the effect of tree depth and splitting criteria.
"""

import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

from google.colab import drive
drive.mount('/content/drive')

path= "/content/drive/MyDrive/ml_dataset/daily_weather.csv"
df=pd.read_csv(path)
df.head(5)

df.info()

df.head()

print(df)

df.shape

df.describe()

df.columns

#Data Cleaning: Output "True" --> means that there are some null values
df.isnull().any().any()

df.isnull().sum()

#Print the rows with missing values.
df[df.isnull().any(axis = 1)]

#We do not need to number the rows as Pandas provides it's own indexing.
del df['number']
df.columns

df.shape

before_rows = df.shape[0]
df = df.dropna()
after_rows = df.shape[0]

print("Before rows: ", before_rows)
print("After rows: ", after_rows)
print("The number of dropped rows are: ", before_rows - after_rows)
#print("The number of dropped rows are ()".format(before_rows - after_rows))

df.shape

clean_data=df.copy()
clean_data['high_humidity_label']=(clean_data['relative_humidity_3pm']>24.99)*1
print(clean_data['high_humidity_label'])

clean_data.columns

clean_data.shape

#We do not need to 'relative humidity 9am' and 'relative humidity 3pm'the rows
del clean_data['relative_humidity_9am']
del clean_data['relative_humidity_3pm']
clean_data.columns

clean_data.shape

##Split dataset into independent and dependant features.
X=clean_data.iloc[:,:-1]
print(X)

y=clean_data.iloc[:,-1]
print(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, test_size = 0.3, random_state = 42)

X_test

X_train

y_test

y_train

#Fit the model on the training set using the Decision Tree Classifier
humidity_classifier = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)
humidity_classifier.fit(X_train, y_train)

import matplotlib.pyplot as plt
from sklearn import tree
plt.figure(figsize=(15,10))
tree.plot_tree(humidity_classifier, filled=True)

#prediction
y_pred = humidity_classifier.predict(X_test)
print(y_pred)

#Accuracy Score, Classification Report and Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(y_pred, y_test))

accuracy = accuracy_score(y_pred, y_test)

print rprintprinrprintprintprintinrprintprintprintintttprintinrprintprintprintintt(accuracy)

print(classification_report(y_pred, y_test))