# -*- coding: utf-8 -*-
"""ML PRAC 4 SANIKA EXTRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19MC4Jx5f1d5sNAxVSQSKwtaOAiCm15Ni

Sanika Takarkhede(CS23016)
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount("/content/drive")

path = "/content/drive/MyDrive/ML_dataset/Developer_Performance_dataset_1000.csv"
df = pd.read_csv(path)

df.head(5)

df.info()

df.shape

df.describe()

df.columns

df.isnull().any().any()

df.isnull().sum()

df[df.isnull().any(axis=1)]

before_rows = df.shape[0]
df = df.dropna()
after_rows = df.shape[0]

print("Before rows:", before_rows)
print("After rows:", after_rows)
print("The number of dropped rows are:", before_rows - after_rows)

df.shape

X = df.iloc[:, :-1]
print(X)

from sklearn.model_selection import train_test_split
Y = df.iloc[:, -1]
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.3, random_state=42
)

X_train

X_test

Y_train

Y_test

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_squared_error, r2_score

depths = [2, 4, 6, 8]
criteria = ["squared_error", "friedman_mse"]

for criterion in criteria:
    for depth in depths:
        regressor = DecisionTreeRegressor(
            max_depth=depth,
            criterion=criterion,
            random_state=0
        )
        regressor.fit(X_train, Y_train)

        Y_pred = regressor.predict(X_test)

        print("Criterion:", criterion)
        print("Max Depth:", depth)
        print("Mean Squared Error:", mean_squared_error(Y_test, Y_pred))
        print("R2 Score:", r2_score(Y_test, Y_pred))
        print("----------------------------------")

import matplotlib.pyplot as plt
from sklearn import tree

best_regressor = DecisionTreeRegressor(max_depth=4, random_state=0)
best_regressor.fit(X_train, Y_train)

plt.figure(figsize=(10,10))
tree.plot_tree(best_regressor, filled=True)
plt.show()