# -*- coding: utf-8 -*-
"""Hericharical Clustering using agglomertaive methods

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZ_K2TdDgDHX_mmBMRUvKKkHtM3E5GNS

Sanika Takarkhed(CS23016)

AIM: to perform hericharical clustering using agglomertaive methods and interpret dendrograms for cluster formation
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage

from google.colab import drive
drive.mount('/content/drive')

path ="/content/drive/MyDrive/ML_DATASET/Mall_Customers - Mall_Customers.csv"
df=pd.read_csv(path)
df.head(5)

X = df[['Annual Income (k$)','Spending Score (1-100)']]

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

plt.figure(figsize=(8,5))
dendrogram(linkage(X_scaled,method='ward'))
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Euclidean Distance')
plt.show()

hc=AgglomerativeClustering(n_clusters=5,metric='euclidean',linkage='ward')
clusters=hc.fit_predict(X_scaled)

df['Cluster']=clusters
print(df.head())

plt.figure(figsize=(8,6))
sns.scatterplot(x='Annual Income (k$)',y='Spending Score (1-100)',hue='Cluster',data=df,palette='viridis')
plt.title("Hierarchical Clustering of Mall Customer")
plt.show()

