# -*- coding: utf-8 -*-
"""prac9 ML Sanika (CS23016).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVrkDfpwmWDk4cCVb61rJuxR7oERBk0k

Sanika Takarkhede(CS23016)

Aim:To implement the K:Mean clustering algorithm and analyze yhe clustering results using appropriate evaulation techniques
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

path="/content/drive/MyDrive/ML_dataset/Mall_Customers - Mall_Customers.csv"
df=pd.read_csv(path)
df.head(5)

df.shape

df.columns

df.describe()

df.info()

df.isnull().any().any()

df[df.isnull().any(axis=1)]

df.isnull().sum()

X = df.iloc[:, [3, 4]].values
print(X)

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

inertia_values = []

for k in range(1, 11):
  kmeans = KMeans(n_clusters=k, random_state=42)
  kmeans.fit(X_scaled)
  inertia_values.append(kmeans.inertia_)

print(inertia_values)

plt.figure()
plt.plot(range(1, 11), inertia_values, marker='o')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method for optimal K')

from sklearn import cluster
kmeans=KMeans(n_clusters=5,random_state=42)
cluster=kmeans.fit_predict(X_scaled)
df['cluster']=cluster
print(df.head())

print("inertia:",kmeans.inertia_)
sil_score=silhouette_score(X_scaled,cluster)
print("silhouette score",sil_score)

plt.figure()
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='cluster', data=df, palette='Set1')
centroids=scaler.inverse_transform(kmeans.cluster_centers_)
plt.scatter(centroids[:, 0], centroids[:, 1], s=200, c='black', marker='X', label='Centroids')
plt.title("Customer Segmentation using K-Means")
plt.legend()
plt.show()

kmeans=KMeans(n_clusters= 3,random_state=42)
cluster=kmeans.fit_predict(X_scaled)
df['cluster']=cluster
print(df.head())

print("inertia:",kmeans.inertia_)
sil_score=silhouette_score(X_scaled,cluster)
print("silhouette score",sil_score)

plt.figure()
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='cluster', data=df, palette='Set1')
centroids=scaler.inverse_transform(kmeans.cluster_centers_)
plt.scatter(centroids[:, 0], centroids[:, 1], s=200, c='black', marker='X', label='Centroids')
plt.title("Customer Segmentation using K-Means")
plt.legend()
plt.show()

kmeans=KMeans(n_clusters=8,random_state=42)
cluster=kmeans.fit_predict(X_scaled)
df['cluster']=cluster
print(df.head())



print("inertia:",kmeans.inertia_)
sil_score=silhouette_score(X_scaled,cluster)
print("silhouette score",sil_score)

plt.figure()
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='cluster', data=df, palette='Set1')
centroids=scaler.inverse_transform(kmeans.cluster_centers_)
plt.scatter(centroids[:, 0], centroids[:, 1], s=200, c='black', marker='X', label='Centroids')
plt.title("Customer Segmentation using K-Means")
plt.legend()
plt.show()

from sklearn import cluster
kmeans=KMeans(n_clusters=4,random_state=42)
cluster=kmeans.fit_predict(X_scaled)
df['cluster']=cluster
print(df.head())

print("inertia:",kmeans.inertia_)
sil_score=silhouette_score(X_scaled,cluster)
print("silhouette score",sil_score)



plt.figure()
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='cluster', data=df, palette='Set1')
centroids=scaler.inverse_transform(kmeans.cluster_centers_)
plt.scatter(centroids[:, 0], centroids[:, 1], s=200, c='black', marker='X', label='Centroids')
plt.title("Customer Segmentation using K-Means")
plt.legend()
plt.show()

from sklearn import cluster
kmeans=KMeans(n_clusters=7,random_state=42)
cluster=kmeans.fit_predict(X_scaled)
df['cluster']=cluster
print(df.head())



from sklearn import cluster
kmeans=KMeans(n_clusters=6,random_state=42)
cluster=kmeans.fit_predict(X_scaled)
df['cluster']=cluster
print(df.head())