# -*- coding: utf-8 -*-
"""Prac 8 ML Extra Sanika (CS23016)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176rmx3SO6rUNNaAMW-BrJ6GVmWWdyl1c

Lab 8 Extra Practical: To perform Linear Discriminant Analysis (LDA) and Principal Component Analysis (PCA) separately on a dataset, apply Logistic Regression on the transformed features, and compare the performance of LDA-based and PCA-based models.
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

iris=load_iris()
x=iris.data
y=iris.target

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/ML_DATASET/Breast_Cancer_dataset - Breast_Cancer_dataset.csv")
df.head()

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

lda = LDA(n_components=2)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

lr_lda = LogisticRegression()
lr_lda.fit(X_train_lda, y_train)

y_pred_lda = lr_lda.predict(X_test_lda)

print("LDA Model Accuracy:", accuracy_score(y_test, y_pred_lda))
print(classification_report(y_test, y_pred_lda))

print("Accuracy using PCA:", accuracy_score(y_test, y_pred_pca))
print("Accuracy using LDA:", accuracy_score(y_test, y_pred_lda))

lda = LinearDiscriminantAnalysis(n_components=2)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

model_lda = LogisticRegression()
model_lda.fit(X_train_lda, y_train)
y_pred_lda = model_lda.predict(X_test_lda)

print("LDA Accuracy:", accuracy_score(y_test, y_pred_lda))

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

from sklearn.metrics import classification_report
lr_pca = LogisticRegression()
lr_pca.fit(X_train_pca, y_train)

y_pred_pca = lr_pca.predict(X_test_pca)

print("PCA Model Accuracy:", accuracy_score(y_test, y_pred_pca))
print(classification_report(y_test, y_pred_pca))

lda = LDA(n_components=2)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

lr_lda = LogisticRegression()
lr_lda.fit(X_train_lda, y_train)

y_pred_lda = lr_lda.predict(X_test_lda)

print("LDA Model Accuracy:", accuracy_score(y_test, y_pred_lda))
print(classification_report(y_test, y_pred_lda))