# -*- coding: utf-8 -*-
"""parc 8 sanika ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v47GBOXrIuB2mIB_UQz_iZ6XRoANDLfd

Aim:To apply Principal Compoment Analysis for dimensionality reduction and visualize the transformed feature space
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

iris=load_iris()
X=iris.data
y=iris.target

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
#PRINT(X_scaled)

PCA=PCA(n_components=2)
X_pca=PCA.fit_transform(X_scaled)
#print (X_pca)

print("Explained variance ratio:",PCA.explained_variance_ratio_)

plt.figure(figsize=(8,6))
plt.scatter(X_pca[:,0],X_pca[:,1],c=y)
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("PCA Visualization")
plt.show()

import sklearn.decomposition
pca=sklearn.decomposition.PCA()
pca.fit(X_scaled)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel("Number of components")
plt.ylabel("Cumulative explained variance")
plt.title("Explained variance by components")
plt.show()