# -*- coding: utf-8 -*-
"""Prac 5  Extra ML Sanika (CS23016)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzBN6r_eks9HmcEK7WuRku-Rio5GIgPW

Lab 5 Extra Practical: To implement the Random Forest algorithm on the Gaming and Mental Health dataset and evaluate the model performance using appropriate metrics.
"""

import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

from google.colab import drive
drive.mount('/content/drive')

path= "/content/drive/MyDrive/ML_DATASET/Gaming and Mental Health - Gaming and Mental Health.csv"
df=pd.read_csv(path)
df.head(5)

df.shape

df.columns

df.info()

df.isnull().any().any()

df.isnull().sum()

df[df.isnull().any(axis=1)]

df.describe()

x=df.drop(columns=['gaming_addiction_risk_level'])
y=df['gaming_addiction_risk_level']

x.head()

x=pd.get_dummies(x)

x=pd.get_dummies(x,dtype=int)

x.head()

x.shape

x.columns

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.7, test_size= 0.25, random_state=42)
x_train.shape,x_test.shape

#fit the model on the training set using the decision tree classifier
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=100,n_jobs=-1,max_depth=5,oob_score=True,random_state=42)
rf_classifier.fit(x_train,y_train)

#prediction
y_pred=rf_classifier.predict(x_test)
#print(y_pred)

#accurecy score ,classification report and confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print('confusion matrix')
cm=confusion_matrix(y_pred,y_test)
print(confusion_matrix(y_pred,y_test))

print('accuracy score')
print(accuracy_score(y_pred,y_test))

#check the oob score
rf_classifier.oob_score_

rf=RandomForestClassifier(random_state=42,n_jobs=-1)
params={
    'max_depth':[2,3,5,10,20],
    'min_samples_leaf':[5,10,20,50,100,200],
    'n_estimators':[10,25,30,50,100,200]
}
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(estimator=rf,param_grid=params,cv=4,n_jobs=-1,verbose=1,scoring='accuracy')
grid_search.fit(x_train,y_train)

grid_search.best_score_

print(grid_search.best_params_)