# -*- coding: utf-8 -*-
"""PRAC 7 ML Extra Sanika(CS23016)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSDma9ck4KMsPvdFqYLAgsACEjTdmQAh

Lab 7 Extra Practical: To apply Support Vector Machine for Regression on Students Performance Dataset and analyze the impact of different kernels on model accuracy.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
path= "/content/drive/MyDrive/ML_DATASET/Student_Performance_dataset_5000 - Student_Performance_dataset_5000.csv"
df=pd.read_csv(path)
df.head(5)

df.shape

df.columns

new_columns = {
    'Mean of the integrated profile': 'IP_Mean',
    'Standard deviation of the integrated profile': 'IP_Std',
    'Excess kurtosis of the integrated profile': 'IP_Kurtosis',
    'Skewness of the integrated profile': 'IP_Skewness',
    'Mean of the DM-SNR curve': 'DM_Mean',
    'Standard deviation of the DM-SNR curve': 'DM_Std',
    'Excess kurtosis of the DM-SNR curve': 'DM_Kurtosis',
    'Skewness of the DM-SNR curve': 'DM_Skewness',
    'target_class': 'Class'
}
df.columns = df.columns.str.strip()
df.columns = df.columns.str.strip()

# Then, rename using the provided mapping.
# The keys in new_columns should now match the stripped column names.
df.rename(columns=new_columns, inplace=True)



print(df.columns)




df.describe()

df.info()

df.isnull().any().any()

df[df.isnull().any(axis = 1)]

df.isnull().sum()

X=df.drop(columns=['exam_score'])
y=df['exam_score']

X.head()

X.columns

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=42)

X_train.shape,X_test.shape

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify categorical and numerical columns
categorical_cols = X.select_dtypes(include=['object']).columns
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns

# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ])

# Apply the preprocessor to X_train and X_test
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

# If you want to convert back to DataFrame for inspection (optional)
# feature_names = list(numerical_cols) + list(preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols))
# X_train = pd.DataFrame(X_train_processed, columns=feature_names, index=X_train.index)
# X_test = pd.DataFrame(X_test_processed, columns=feature_names, index=X_test.index)

# Update X_train and X_test to their processed versions
X_train = X_train_processed
X_test = X_test_processed

X_train

X_test

from sklearn.svm import SVR # Changed SVC to SVR
from sklearn.metrics import r2_score, mean_squared_error # Changed accuracy_score to r2_score and mse

# 1. Initialize the model
svr = SVR() # Changed svc to svr

# 2. Train the model
svr.fit(X_train, y_train)

# 3. Make predictions
y_pred = svr.predict(X_test)

# 4. Print regression metrics
print('Model R-squared score with default hyperparameters: {0:0.4f}'.format(r2_score(y_test, y_pred)))
print('Model Mean Squared Error with default hyperparameters: {0:0.4f}'.format(mean_squared_error(y_test, y_pred)))

from sklearn.svm import SVR # Changed SVC to SVR
from sklearn.metrics import r2_score, mean_squared_error # Changed accuracy_score to r2_score and mse

# 1. Initialize the model
svr = SVR(C=100.0) # Changed svc to svr

# 2. Train the model
svr.fit(X_train, y_train)

# 3. Make predictions
y_pred = svr.predict(X_test)

# 4. Print regression metrics
print('Model R-squared score with default hyperparameters: {0:0.4f}'.format(r2_score(y_test, y_pred)))
print('Model Mean Squared Error with default hyperparameters: {0:0.4f}'.format(mean_squared_error(y_test, y_pred)))

from sklearn.svm import SVR # Changed SVC to SVR
from sklearn.metrics import r2_score, mean_squared_error # Changed accuracy_score to r2_score and mse

# 1. Initialize the model
svr = SVR(C=1000.0) # Changed svc to svr

# 2. Train the model
svr.fit(X_train, y_train)

# 3. Make predictions
y_pred = svr.predict(X_test)# 4. Print regression metrics
print('Model R-squared score with C=1000.0: {0:0.4f}'.format(r2_score(y_test, y_pred)))
print('Model Mean Squared Error with C=1000.0: {0:0.4f}'.format(mean_squared_error(y_test, y_pred)))

from sklearn.svm import SVR # Use SVR for regression
from sklearn.metrics import r2_score, mean_squared_error # Use regression metrics

# 1. Initialize the SVR model with a linear kernel
linear_svr = SVR(kernel='linear') # Changed SVC to SVR

# 2. Train the model
linear_svr.fit(X_train, y_train)

# 3. Make predictions
y_pred_linear = linear_svr.predict(X_test)

# 4. Print regression metrics
print('Linear SVR R-squared score: {0:0.4f}'.format(r2_score(y_test, y_pred_linear)))
print('Linear SVR Mean Squared Error: {0:0.4f}'.format(mean_squared_error(y_test, y_pred_linear)))

# Regression Metrics
from sklearn.metrics import r2_score, mean_squared_error

# Assuming y_test and y_pred are already available from the last SVR model
print('R-squared score: {0:0.4f}'.format(r2_score(y_test, y_pred_linear)))
print('Mean Squared Error: {0:0.4f}'.format(mean_squared_error(y_test, y_pred_linear)))

# print('Confusion Matrix:')
# cm=confusion_matrix(y_test,y_pred)
# print(confusion_matrix(y_test, y_pred))

# The confusion matrix is not applicable for regression tasks as it is a classification metric.
# For regression, metrics like R-squared and Mean Squared Error are used, which have already been calculated.

# print(cm) # The variable 'cm' was not defined as confusion matrix is not applicable for regression.

print('classification report')
# print(classification_report(y_test, y_pred)) # Classification report is not applicable for regression.