# -*- coding: utf-8 -*-
"""ml_pract7 SANIKA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOw2BwQ7kk3ZeRs89Z8u1DnIH82v8JIT

Sanika Tkarkhede(CS23016)
ml_lab_7

aim:to apply support vector machine for classification and analysis the impact of differnt kernels on model accuracy
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from google.colab import drive
drive.mount('/content/drive')

path= "/content/drive/MyDrive/ml_dataset/pulsar_stars.csv"
df=pd.read_csv(path)
df.head(5)

df.shape

df.columns

new_columns = {
    'Mean of the integrated profile': 'IP_Mean',
    'Standard deviation of the integrated profile': 'IP_Std',
    'Excess kurtosis of the integrated profile': 'IP_Kurtosis',
    'Skewness of the integrated profile': 'IP_Skewness',
    'Mean of the DM-SNR curve': 'DM_Mean',
    'Standard deviation of the DM-SNR curve': 'DM_Std',
    'Excess kurtosis of the DM-SNR curve': 'DM_Kurtosis',
    'Skewness of the DM-SNR curve': 'DM_Skewness',
    'target_class': 'Class'
}
df.columns = df.columns.str.strip()
df.columns = df.columns.str.strip()

# Then, rename using the provided mapping.
# The keys in new_columns should now match the stripped column names.
df.rename(columns=new_columns, inplace=True)



print(df.columns)




df.describe()

df.info()

df.isnull().any().any()

df[df.isnull().any(axis = 1)]

df.isnull().sum()

X=df.drop(columns=['Class'])
y=df['Class']

X.head()

X.columns

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=42)

X_train.shape,X_test.shape

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

X_train

X_test

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc = SVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
print('Model accuracy score with default hyperparameters: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc = SVC(C=100.0)
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
print('Model accuracy score with default hyperparameters: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc = SVC(C=1000.0)
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
print('Model accuracy score with default hyperparameters: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

linear = SVC(kernel='linear')
linear.fit(X_train, y_train)
y_pred = linear.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

linear = SVC(kernel='linear',C=100.0)
linear.fit(X_train, y_train)
y_pred = linear.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

linear = SVC(kernel='linear',C=1000.0)
linear.fit(X_train, y_train)
y_pred = linear.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

poly = SVC(kernel='poly')
poly.fit(X_train, y_train)
y_pred = poly.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

poly = SVC(kernel='poly', C=100.0)
poly.fit(X_train, y_train)
y_pred = poly.predict(X_test)
print('Model accuracy score with polynomial kernel and C=100.0 : {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

poly = SVC(kernel='poly', C=1000.0)
poly.fit(X_train, y_train)
y_pred = poly.predict(X_test)
print('Model accuracy score with polynomial kernel and C=100.0 : {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

sigmoid = SVC(kernel='sigmoid',C=1.0)
sigmoid.fit(X_train, y_train)

sigmoid = SVC(kernel='sigmoid',C=100.0)
sigmoid.fit(X_train, y_train)

sigmoid = SVC(kernel='sigmoid',C=1000.0)
sigmoid.fit(X_train, y_train)

#Accuracy Score Classification report and confusion matrix
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy_score(y_test, y_pred)

print('Confusion Matrix:')
cm=confusion_matrix(y_test,y_pred)
print(confusion_matrix(y_test, y_pred))

print(cm)

print('classification report')
print(classification_report(y_test, y_pred))